Repository be15-fin-tomato/be15-fin-tomato-katchup-BE, pull requests merged in 2025-07, with the labels that each got.

#107 Tmt 165 fe 인스타그램 게시물 통계 조회 기능
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Instagram.java
  src/main/java/be15fintomatokatchupbe/oauth/exception/OAuthErrorCode.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/request/InstagramPermalinkRequest.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramPostInsightResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramRedisService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramTokenService.java
  src/main/java/be15fintomatokatchupbe/relation/repository/PipeInfClientManagerRepository.java
Labels: feat

#110 feat: 파이프라인 삭제 기능 구현
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ContractCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ProposalCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/QuotationCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
  src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
Labels: feat

#112 Tmt 162 be 알림 기능 구현
  .gitignore
  build.gradle
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
  src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
  src/main/java/be15fintomatokatchupbe/chat/command/application/dto/response/ChatResponseDTO.java
  src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/ChatRoomRepository.java
  src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/UserChatRepository.java
  src/main/java/be15fintomatokatchupbe/chat/query/application/mapper/UserChatMapper.java
  src/main/java/be15fintomatokatchupbe/config/FcmConfig.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/controller/FcmController.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationCommandController.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/dto/request/FcmTokenRequest.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/dto/request/NotificationCreateRequest.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/service/FcmService.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/Notification.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/NotificationType.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/repository/NotificationRepository.java
  src/main/java/be15fintomatokatchupbe/notification/exception/NotificationErrorCode.java
  src/main/java/be15fintomatokatchupbe/notification/query/controller/NotificationQueryController.java
  src/main/java/be15fintomatokatchupbe/user/command/application/repository/UserRepository.java
  src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/User.java
  src/main/resources/mappers/chat/UserChatMapper.xml
  src/main/resources/static/fcm-test.html
  src/main/resources/static/firebase-messaging-sw.js
Labels: feat

#117 Tmt 174 fe 인스타그램 데이터 저장 스케줄러 로직 구현
  src/main/java/be15fintomatokatchupbe/Be15FinTomatoKatchupBeApplication.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramSchedulerTestController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramPostInsight.java
  src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/repository/InstagramPostInsightRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/query/repository/InstagramStatsSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsSnapshotService.java
  src/main/java/be15fintomatokatchupbe/relation/repository/PipeInfClientManagerRepository.java
Labels: feat

#123 feat/ 유튜브 댓글 가져오기
  build.gradle
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/SearchRatioQueryService.java
  src/main/java/be15fintomatokatchupbe/influencer/query/controller/YoutubeController.java
  src/main/java/be15fintomatokatchupbe/influencer/query/service/YoutubeService.java
  src/main/java/be15fintomatokatchupbe/oauth/exception/OAuthErrorCode.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
Labels: feat

#127 Tmt 190 be 인스타 댓글 갖고오기
  src/main/java/be15fintomatokatchupbe/notification/query/service/NotificationQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/CommentInfo.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramPostInsightResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
Labels: feat

#129 Tmt 193 be 인스타그램 통계 조회 로직 수정
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InstagramRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramAccountQueryService.java
Labels: fix

#130 Tmt 156 be 캠페인 목록 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepDto.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepStatusDto.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/PipelineStepMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
  src/main/resources/mappers/campaign/PipelineStepMapper.xml
Labels: feat, fix

#136 Fix: 이미지 조회기능 수정
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
  src/main/java/be15fintomatokatchupbe/user/command/application/controller/UserCommandController.java
  src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
  src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/User.java
  src/test/java/be15fintomatokatchupbe/user/command/application/service/UserCommendServiceTest.java
Labels: feat

#138 Tmt 201 be 인스타그램 댓글 요약
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
Labels: feat

#139 Feat: 헤더에서 내 기본정보 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserAccountQueryResponse.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserHeaderAccountResponse.java
  src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
  src/main/java/be15fintomatokatchupbe/user/query/service/UserQueryService.java
  src/main/resources/mappers/user/UserQueryMapper.xml
Labels: feat

#143 Tmt 207 be 전체 수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/SearchRatioQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/SearchRatioQueryMapper.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/SearchRatioQueryService.java
  src/main/java/be15fintomatokatchupbe/influencer/query/controller/YoutubeController.java
Labels: fix

#145 Refactor/quotation
  src/main/java/be15fintomatokatchupbe/auth/query/service/AuthQueryService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/IdeaCommandController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/BasePipelineRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateChanceRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/UpdateChanceRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/IdeaQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/IdeaDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/PipelineSearchRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/IdeaQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/IdeaQueryService.java
  src/main/java/be15fintomatokatchupbe/client/command/application/support/ClientHelperService.java
  src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
  src/main/java/be15fintomatokatchupbe/utils/jwt/JwtTokenProvider.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
  src/main/resources/mappers/campaign/IdeaQueryMapper.xml
Labels: fix

#147 Fix: 비밀번호 변경 수정
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
  src/main/java/be15fintomatokatchupbe/user/command/application/repository/UserRepository.java
  src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
  src/main/java/be15fintomatokatchupbe/user/exception/UserErrorCode.java
  src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
Labels: fix

#149 Fix/notification
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
  src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/java/be15fintomatokatchupbe/config/security/JwtAuthenticationFilter.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationScheduler.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationSseController.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/service/NotificationSchedulerService.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/Notification.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/repository/SseEmitterRepository.java
  src/main/java/be15fintomatokatchupbe/notification/query/dto/NotificationsAllDTO.java
  src/main/resources/mappers/notification/NotificationQueryMapper.xml
Labels: fix

#150 Fix: 이메일시스템쪽 코드 수정
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandService.java
  src/main/java/be15fintomatokatchupbe/chat/command/application/controller/ChatSocketController.java
  src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
  src/main/java/be15fintomatokatchupbe/email/command/domain/aggregate/Satisfaction.java
  src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionDTO.java
  src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/dto/response/NotificationPipeLineResponse.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/service/NotificationSchedulerService.java
  src/main/java/be15fintomatokatchupbe/notification/command/domain/aggregate/Notification.java
  src/main/java/be15fintomatokatchupbe/notification/query/dto/NotificationsAllDTO.java
  src/main/resources/mappers/calendar/TodayScheduleCommandMapper.xml
  src/main/resources/mappers/email/EmailQueryMapper.xml
Labels: fix

#151 Tmt 216 be 카테고리 목록 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/influencer/query/controller/InfluencerQueryController.java
  src/main/java/be15fintomatokatchupbe/influencer/query/mapper/InfluencerMapper.java
  src/main/java/be15fintomatokatchupbe/influencer/query/service/InfluencerQueryService.java
  src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
Labels: feat

#152 feat: 읽지 않은 채팅 수 구현
  src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepository.java
  src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepositoryCustom.java
  src/main/java/be15fintomatokatchupbe/chat/command/domain/repository/MessageMongoRepositoryImpl.java
  src/main/java/be15fintomatokatchupbe/chat/query/application/dto/response/ChatRoomDetailResponse.java
  src/main/java/be15fintomatokatchupbe/chat/query/application/service/ChatQueryService.java
Labels: feat

#154 Tmt 220 be 인플루언서 조회 쿼리 수정
  src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InfluencerCardResponse.java
  src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
Labels: fix

#155 Tmt 224 be 메인 대시보드 조회 기능 로직 수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/MainDashboardQueryController.java
Labels: fix

#156 Tmt 222 be 템플릿 저장 수정
  src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractCommandController.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/ObjectCreateRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
  src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
Labels: feat

#157 fix: 전화번호 빈 배열 가능하도록 수정
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/common/validation/validator/PhoneNumberValidator.java
Labels: fix

#160 Tmt 235 be 메인 대시보드 조회 쿼리 수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ContractResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ProposalResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/QuotationResponse.java
  src/main/resources/mappers/dashboard/MainDashboardQueryMapper.xml
Labels: fix

#163 Tmt 239 be 인스타그램 정보 조회 쿼리 수정
  src/main/java/be15fintomatokatchupbe/influencer/query/dto/response/InstagramInfoResponse.java
  src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
Labels: fix

#165 Tmt 240 be 유튜브 대시보드 데이터 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Influencer.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Youtube.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/Service/YoutubeCommandService.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/YoutubeCommandController.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/domain/YoutubeStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/domain/YoutubeVideoSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/InstagramPostInsightRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/InstagramStatsSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/YoutubeStatsSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/YoutubeVideoSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/scheduler/YoutubeStatsSnapshotScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeStatsResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramAccountSnapshotService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
  src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsServiceTest.java
  src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryServiceTest.java
Labels: feat, fix

#166 Tmt 247 be 유튜브 스냅샷 테이블 조회 기능 추가
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeVideoInfo.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeStatsResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/mapper/YoutubeQueryMapper.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeSnapshotQueryService.java
  src/main/resources/mappers/oauth/youtubeQueryMapper.xml
Labels: feat, fix

#168 Fix: 응답일 null일때만 채우기
  src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
Labels: fix

#172 Fix: 쿼리 수정
  src/main/resources/mappers/email/EmailQueryMapper.xml
Labels: fix

#173 chore: 테라폼 gitignore 추가
  .gitignore
Labels: fix

#177 리스트업 목록 조회
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ListupCardDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ListupFormDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupCardResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupDetailResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ListupSearchResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#178 feat: 캠페인 성과 조회 구현 수정
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/CampaignResultRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#179 fix: 사원 단독 삭제 서비스 트랜잭션 처리
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientManagerCommandService.java
Labels: fix

#182 Tmt 256 be 유튜브 계정 통계 연령대 응답 구조 수정
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeSnapshotQueryService.java
  src/main/resources/mappers/oauth/youtubeQueryMapper.xml
Labels: fix

#183 fix: 리스트업 캠페인 검색 개발
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/CampaignStatusConstants.java
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/CampaignWithCategoryDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignAiResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#188 Fix/campaign search
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/ContractListRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/Exam.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepStatusDto.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
  src/main/resources/mappers/email/EmailQueryMapper.xml
Labels: fix

#190 Tmt 267 be 인플루언서별 진행 캠페인 조회 쿼리 수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignResponse.java
  src/main/resources/mappers/dashboard/PlatformDashboardQueryMapper.xml
Labels: fix

#191 성과 필터링be
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/java/be15fintomatokatchupbe/influencer/query/dto/request/InfluencerListRequestDTO.java
  src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
Labels: fix

#192 캠페인 페이지네이션 수정
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignListResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#196 fix: 계약 목록 조회에서 총수익을 (판매수량 * 판매가격)으로 수정
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: fix

#195 Tmt 269 성과목록 조회
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/CampaignResultRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignInfluencerInfo.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignResultResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: feat

#193 Tmt 270 be 성과 대시보드 이동 위해 picm id 조회 추가
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignResponse.java
  src/main/resources/mappers/dashboard/PlatformDashboardQueryMapper.xml
Labels: fix

#200 성과 백수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueDTO.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/CampaignDashboardQueryMapper.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
  src/main/resources/mappers/dashboard/CampaignDashboardQueryMapper.xml
Labels: feat

#205 fix: 캠페인 고객사 커뮤니케이션 스텝 중복 이슈 수정
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#208 Tmt 287 be 인스타 유튜브 api 응답 수정
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramSchedulerTestController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramMediaSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/domain/InstagramStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramFullSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramMediaStats.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramStatsResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/scheduler/InstagramInsightScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramAccountQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsSnapshotService.java
  src/main/resources/mappers/oauth/instagramQueryMapper.xml
Labels: fix

#211 Fix: 알림 로직 수정 및 만족도 로직 수정
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/java/be15fintomatokatchupbe/config/WebConfig.java
  src/main/java/be15fintomatokatchupbe/notification/command/application/controller/NotificationSseController.java
  src/main/resources/static/fcm-test.html
  src/main/resources/static/firebase-messaging-sw.js
Labels: fix

#212 Tmt 297 be 파이프라인 인플루언서 아이디 필드 추가
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyContractDto.java
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: feat, fix

#214 Test/test code
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateContractRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateListupRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateRevenueRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/UpdateContractRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/UpdateListupRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientManagerRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/UpdateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/UpdateClientManagerRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/ContractObjectUpdateRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/DetailCreateRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/DetailUpdateRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/dto/request/ObjectCreateRequest.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/EmailSendingService.java
  src/main/java/be15fintomatokatchupbe/contract/query/dto/request/ContractSuccessRequest.java
  src/main/java/be15fintomatokatchupbe/contract/query/dto/response/DetailInfoResponse.java
  src/main/java/be15fintomatokatchupbe/contract/query/dto/response/DetailListResponse.java
  src/test/java/be15fintomatokatchupbe/Be15FinTomatoKatchupBeApplicationTests.java
  src/test/java/be15fintomatokatchupbe/auth/command/service/AuthCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/auth/query/service/AuthQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/calendar/command/application/service/CalendarCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/ContractCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/IdeaCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/ListupCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/ProposalCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/QuotationCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/campaign/query/service/IdeaQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/chat/command/application/service/ChatCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/chat/query/application/service/ChatQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientManagerCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/contract/command/application/service/ContractSuccessCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandServiceTest.java
  src/test/java/be15fintomatokatchupbe/contract/query/service/ContractQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/contract/query/service/ContractSuccessQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/dashboard/query/service/MainDashboardQueryServiceTest.java
  src/test/java/be15fintomatokatchupbe/user/command/application/service/UserCommendServiceTest.java
  src/test/java/be15fintomatokatchupbe/user/query/service/UserQueryServiceTest.java
Labels: feat

#216 Refactor: scheduler package 이동
  src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/YoutubeCommandController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramSchedulerTestController.java
  src/main/java/be15fintomatokatchupbe/oauth/scheduler/InstagramInsightScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/scheduler/YoutubeStatsSnapshotScheduler.java
Labels: fix

#217 Fix/campaign query
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#221 Tmt 303 be 인스타그램 연동 기능 수정
  src/main/java/be15fintomatokatchupbe/calendar/query/controller/CalendarQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Instagram.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InstagramRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/InstagramCommandController.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/SchedulerTestController.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/controller/YoutubeCommandController.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/domain/InstagramMediaSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/domain/InstagramPostInsight.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/domain/InstagramStatsSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/InstagramMediaSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/InstagramPostInsightRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/command/application/repository/InstagramStatsSnapshotRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/exception/OAuthErrorCode.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/InstagramQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramCommentInfo.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/InstagramFullSnapshot.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeStats.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/InstagramPostInsightResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeCodeResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramPostQueryService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramStatsSnapshotService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/InstagramTokenService.java
  src/main/java/be15fintomatokatchupbe/oauth/scheduler/InstagramScheduler.java
  src/main/java/be15fintomatokatchupbe/oauth/scheduler/YoutubeScheduler.java
  src/main/resources/application.yml
  src/main/resources/mappers/oauth/instagramQueryMapper.xml
  src/main/resources/mappers/oauth/youtubeQueryMapper.xml
Labels: feat, fix

#220 feat: time-out 시간 수정
  src/main/resources/application.yml
Labels: fix

#228 fix: 캠페인 목록 조회 쿼리 담당자 매핑 수정
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix

#230 feat: 트래픽 더미 자동 생성
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
  src/main/java/be15fintomatokatchupbe/dashboard/command/application/support/DashboardHelperService.java
  src/main/java/be15fintomatokatchupbe/dashboard/command/domain/aggregate/InfluencerTraffic.java
  src/main/java/be15fintomatokatchupbe/dashboard/command/domain/aggregate/Traffic.java
  src/main/java/be15fintomatokatchupbe/dashboard/command/domain/repository/InfluencerTrafficRepository.java
  src/main/java/be15fintomatokatchupbe/dashboard/command/domain/repository/TrafficRepository.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
  src/main/java/be15fintomatokatchupbe/relation/domain/PipelineInfluencerClientManager.java
  src/main/java/be15fintomatokatchupbe/relation/repository/PipeInfClientManagerRepository.java
  src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
Labels: feat

#233 Tmt 319 be 인플루언서 만족도 조회 쿼리 수정
  src/main/java/be15fintomatokatchupbe/email/query/controller/EmailQueryController.java
  src/main/java/be15fintomatokatchupbe/email/query/dto/response/InfluencerSatisfactionResponse.java
  src/main/java/be15fintomatokatchupbe/email/query/mapper/EmailQueryMapper.java
  src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
  src/main/resources/mappers/email/EmailQueryMapper.xml
Labels: fix

#234 refactor: 전체적인 수정
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/TrafficQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueDTO.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ThumbnailResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/TrafficResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/TrafficQueryMapper.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/TrafficQueryService.java
  src/main/resources/mappers/dashboard/CampaignDashboardQueryMapper.xml
  src/main/resources/mappers/dashboard/TrafficQueryMapper.xml
Labels: feat

#237 refactor: 템플릿 수정
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/exception/ContractErrorCode.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
  src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
Labels: fix

#236 Fix: 선택된 단계까지만 뜨게 변경
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/PipelineStepsDto.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
  src/main/resources/mappers/contract/ContractSuccessQueryMapper.xml
Labels: fix

#239 chore:헬스체크 추가
  build.gradle
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feat

#246 Fix: 프로필 사진 경로 변경
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
Labels: fix

#259 fix:캠페인 삭제 수정
  main.tf
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/RevenueCommandService.java
  src/main/resources/application-dev.yml
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: fix
