Repository be15-fin-tomato/be15-fin-tomato-katchup-BE, pull requests merged in 2025-06, with the labels that each got.

#6 Feat: 비밀번호 변경 구현
  src/main/java/be15fintomatokatchupbe/auth/command/controller/AuthCommandController.java
  src/main/java/be15fintomatokatchupbe/auth/command/service/AuthCommandService.java
  src/main/java/be15fintomatokatchupbe/user/command/application/controller/UserCommandController.java
  src/main/java/be15fintomatokatchupbe/user/command/application/dto/request/ChangePasswordRequest.java
  src/main/java/be15fintomatokatchupbe/user/command/application/repository/UserRepository.java
  src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
  src/main/java/be15fintomatokatchupbe/user/exception/UserErrorCode.java
Labels: feat

#14 Tmt 64 be 내 개인정보 조회 구현
  src/main/java/be15fintomatokatchupbe/common/domain/GenderType.java
  src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/PicFile.java
  src/main/java/be15fintomatokatchupbe/user/query/controller/Exam.java
  src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/Exam.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserAccountQueryResponse.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserInfluencerListDTO.java
  src/main/java/be15fintomatokatchupbe/user/query/dto/response/UserInfluencerListResponse.java
  src/main/java/be15fintomatokatchupbe/user/query/mapper/Exam.java
  src/main/java/be15fintomatokatchupbe/user/query/mapper/UserQueryMapper.java
  src/main/java/be15fintomatokatchupbe/user/query/service/Exam.java
  src/main/java/be15fintomatokatchupbe/user/query/service/UserQueryService.java
  src/main/resources/mappers/user/UserQueryMapper.xml
Labels: feat

#25 Tmt 76 be 고객사 파일 구조 생성 및 헬퍼 폴더 구조 변경
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateChanceRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
  src/main/java/be15fintomatokatchupbe/client/command/application/controller/ClientCompanyCommandController.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientManagerRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/response/CreateClientCompanyResponse.java
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
  src/main/java/be15fintomatokatchupbe/client/command/application/support/ClientHelperService.java
  src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
  src/main/java/be15fintomatokatchupbe/client/query/controller/ClientCompanyQueryController.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyDetailResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyListResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
  src/main/java/be15fintomatokatchupbe/client/query/service/ClientCompanyQueryService.java
  src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
Labels: feat, fix

#23 Feat: 내 계정정보 수정 구현
  src/main/java/be15fintomatokatchupbe/auth/command/controller/AuthCommandController.java
  src/main/java/be15fintomatokatchupbe/auth/query/controller/AuthQueryController.java
  src/main/java/be15fintomatokatchupbe/common/exception/GlobalErrorCode.java
  src/main/java/be15fintomatokatchupbe/config/WebConfig.java
  src/main/java/be15fintomatokatchupbe/user/command/application/controller/UserCommandController.java
  src/main/java/be15fintomatokatchupbe/user/command/application/dto/request/ChangeMyAccountRequest.java
  src/main/java/be15fintomatokatchupbe/user/command/application/repository/PicFileRepository.java
  src/main/java/be15fintomatokatchupbe/user/command/application/service/UserCommendService.java
  src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/PicFile.java
  src/main/java/be15fintomatokatchupbe/user/command/domain/aggregate/User.java
  src/main/java/be15fintomatokatchupbe/user/exception/UserErrorCode.java
  src/main/java/be15fintomatokatchupbe/user/query/controller/UserQueryController.java
Labels: feat

#31 Tmt 80 be 메인 대시보드 계약 조회 기능
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/MainDashboardQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/ContractResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/MainDashboardQueryMapper.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/MainDashboardQueryService.java
  src/main/resources/mappers/dashboard/MainDashboardQueryMapper.xml
Labels: feat

#34 Tmt 78 be 제안 생성 페이지
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/BasePipelineRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateChanceRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateProposalRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/IdeaRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerProposalRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/InfluencerRevenueRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/support/CampaignHelperService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/PipelineStatusConstants.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/constant/PipelineStepConstants.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Campaign.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/CampaignStatus.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/File.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Idea.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/PipelineStatus.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/PipelineStep.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/repository/CampaignRepository.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/repository/IdeaRepository.java
  src/main/java/be15fintomatokatchupbe/campaign/exception/CampaignErrorCode.java
  src/main/java/be15fintomatokatchupbe/influencer/command/application/support/InfluencerHelperService.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/InfluencerRepository.java
  src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandServiceTest.java
Labels: feat

#38 Tmt 77 be 고객사 및 사원 등록 기능 구현
  src/main/java/be15fintomatokatchupbe/client/command/application/controller/ClientCompanyCommandController.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientManagerRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientCompany.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientCompanyStatus.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientManagerStatus.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/constant/ClientCompanyStatusConstants.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/constant/ClientManagerStatusConstants.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientCompanyStatusRepository.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientManagerStatusRepository.java
  src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
  src/main/java/be15fintomatokatchupbe/common/exception/GlobalExceptionHandler.java
  src/main/java/be15fintomatokatchupbe/common/validation/ValidEmail.java
  src/main/java/be15fintomatokatchupbe/common/validation/ValidPhoneNumber.java
  src/main/java/be15fintomatokatchupbe/common/validation/validator/EmailValidator.java
  src/main/java/be15fintomatokatchupbe/common/validation/validator/PhoneNumberValidator.java
  src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandServiceTest.java
Labels: feat

#39 Tmt 93 be 유튜브 analytics api 연동
  .github/workflows/pr-test.yml
  build.gradle
  src/main/java/be15fintomatokatchupbe/config/SecurityConfig.java
  src/main/java/be15fintomatokatchupbe/config/WebClientConfig.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeOAuthQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeStatsResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsService.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
  src/main/resources/application.yml
  src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeAnalyticsServiceTest.java
  src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryServiceTest.java
Labels: feat

#40 Tmt 89 be 제안 목록 조회
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/request/ProposalSearchRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/Exam.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ProposalCardResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ProposalSearchResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/application.yml
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
  src/test/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryServiceTest.java
Labels: feat

#45 Tmt 102 be 견적 등록
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/CreateQuotationRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Campaign.java
  src/main/java/be15fintomatokatchupbe/relation/service/PipeInfClientManagerService.java
  src/test/java/be15fintomatokatchupbe/campaign/command/application/service/CampaignCommandServiceTest.java
Labels: feat

#48 Tmt 105 be 고객사 등록 수정 시 담당자 필드 추가
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/CreateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/dto/request/UpdateClientCompanyRequest.java
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
  src/main/java/be15fintomatokatchupbe/relation/domain/ClientCompanyUser.java
  src/main/java/be15fintomatokatchupbe/relation/repository/ClientCompanyUser.java
  src/main/java/be15fintomatokatchupbe/relation/repository/ClientCompanyUserRepository.java
  src/main/java/be15fintomatokatchupbe/relation/service/ClientCompanyUserService.java
  src/test/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandServiceTest.java
Labels: feat

#44 Tmt 82 be 만족도 조사 목록 조회 구현
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/CampaignSatisfactionDTO.java
  src/main/java/be15fintomatokatchupbe/email/command/application/controller/EmailCommandController.java
  src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/exam.java
  src/main/java/be15fintomatokatchupbe/email/command/application/dto/response/Exam.java
  src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
  src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
  src/main/java/be15fintomatokatchupbe/email/query/controller/EmailQueryController.java
  src/main/java/be15fintomatokatchupbe/email/query/dto/request/EmailSearchRequest.java
  src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionDTO.java
  src/main/java/be15fintomatokatchupbe/email/query/dto/response/CampaignSatisfactionResponse.java
  src/main/java/be15fintomatokatchupbe/email/query/mapper/EmailQueryMapper.java
  src/main/java/be15fintomatokatchupbe/email/query/service/EmailQueryService.java
  src/main/resources/mappers/email/EmailQueryMapper.xml
  src/test/java/be15fintomatokatchupbe/email/query/service/EmailQueryServiceTest.java
Labels: feat

#50 Tmt 93 be 유튜브 analytics api 연동
  src/main/java/be15fintomatokatchupbe/influencer/command/application/service/InfluencerCommandServiceImpl.java
  src/main/java/be15fintomatokatchupbe/influencer/command/application/support/InfluencerHelperService.java
  src/main/java/be15fintomatokatchupbe/influencer/command/application/support/YoutubeHelperService.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/aggregate/entity/Youtube.java
  src/main/java/be15fintomatokatchupbe/influencer/command/domain/repository/YoutubeRepository.java
  src/main/java/be15fintomatokatchupbe/infra/redis/YoutubeTokenRepository.java
  src/main/java/be15fintomatokatchupbe/oauth/query/controller/YoutubeOAuthQueryController.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/YoutubeCodeRequest.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/TokenResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/dto/response/YoutubeCodeResponse.java
  src/main/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryService.java
  src/main/resources/mappers/Influencer/InfluencerQueryMapper.xml
  src/test/java/be15fintomatokatchupbe/oauth/query/service/YoutubeOAuthQueryServiceTest.java
Labels: feat

#55 feat: 파일 업로드, 저장 구현
  .github/workflows/pr-test.yml
  build.gradle
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
  src/main/java/be15fintomatokatchupbe/config/AwsConfig.java
  src/main/java/be15fintomatokatchupbe/file/controller/FileController.java
  src/main/java/be15fintomatokatchupbe/file/domain/File.java
  src/main/java/be15fintomatokatchupbe/file/dto/FileDownloadResult.java
  src/main/java/be15fintomatokatchupbe/file/exception/FileErrorCode.java
  src/main/java/be15fintomatokatchupbe/file/repository/FileRepository.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
  src/main/java/be15fintomatokatchupbe/influencer/command/application/dto/FileDTO.java
  src/main/java/be15fintomatokatchupbe/utils/FileUtil.java
  src/main/resources/application.yml
Labels: feat

#57 Tmt 117 사원 삭제 기능 구현
  src/main/java/be15fintomatokatchupbe/client/command/application/controller/ClientManagerCommandController.java
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientCompanyCommandService.java
  src/main/java/be15fintomatokatchupbe/client/command/application/service/ClientManagerCommandService.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/aggregate/ClientManager.java
  src/main/java/be15fintomatokatchupbe/client/command/domain/repository/ClientManagerRepository.java
  src/main/java/be15fintomatokatchupbe/client/command/exception/ClientErrorCode.java
Labels: feat

#59 Feat: 만족도 조사 평가 요청 구현
  src/main/java/be15fintomatokatchupbe/email/command/application/controller/EmailCommandController.java
  src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/EmailSendSatisfactionRequest.java
  src/main/java/be15fintomatokatchupbe/email/command/application/dto/request/exam.java
  src/main/java/be15fintomatokatchupbe/email/command/application/service/EmailCommendService.java
  src/main/java/be15fintomatokatchupbe/email/command/domain/aggregate/Satisfaction.java
  src/main/java/be15fintomatokatchupbe/email/command/domain/repository/SatisfactionRepository.java
  src/main/java/be15fintomatokatchupbe/email/exception/EmailErrorCode.java
Labels: feat

#63 Tmt 118 be 고객사 및 사원 상세 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/client/query/controller/ClientCompanyQueryController.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyDetailResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientManagerDTO.java
  src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
  src/main/java/be15fintomatokatchupbe/client/query/service/ClientCompanyQueryService.java
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: feat

#66 Tmt 121 be 고객사 사원 목록 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/client/query/controller/ClientManagerQueryController.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientManagerSimpleResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
  src/main/java/be15fintomatokatchupbe/client/query/service/ClientManagerQueryService.java
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: feat

#70 Tmt 135 be 계약 목록 조회
  src/main/java/be15fintomatokatchupbe/campaign/query/controller/CampaignQueryController.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/ContractCardDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/mapper/RevenueCardDTO.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractCardResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/ContractSearchResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/RevenueCardResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/dto/response/RevenueSearchResponse.java
  src/main/java/be15fintomatokatchupbe/campaign/query/mapper/CampaignQueryMapper.java
  src/main/java/be15fintomatokatchupbe/campaign/query/service/CampaignQueryService.java
  src/main/resources/mappers/campaign/CampaignQueryMapper.xml
Labels: feat

#72 Tmt 126 be 해당 고객사 담당하는 mcn 담당자 목록 조회
  src/main/java/be15fintomatokatchupbe/client/query/controller/ClientCompanyQueryController.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyUserResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
  src/main/java/be15fintomatokatchupbe/client/query/service/ClientCompanyQueryService.java
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: feat

#77 Tmt 119 be 고객사 목록 조회 기능 구현
  src/main/java/be15fintomatokatchupbe/client/query/controller/ClientCompanyQueryController.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyListPagedResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/dto/ClientCompanyListResponse.java
  src/main/java/be15fintomatokatchupbe/client/query/mapper/ClientCompanyQueryMapper.java
  src/main/java/be15fintomatokatchupbe/client/query/service/ClientCompanyQueryService.java
  src/main/resources/mappers/client/ClientCompanyQueryMapper.xml
Labels: feat

#86 Tmt 147 be 계약서 파일 등록 구현
  src/main/java/be15fintomatokatchupbe/contract/command/application/controller/ContractSuccessCommandController.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractObjectCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/ContractSuccessCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/command/application/service/DetailCommandService.java
  src/main/java/be15fintomatokatchupbe/contract/command/domain/entity/Contract.java
  src/main/java/be15fintomatokatchupbe/contract/command/domain/entity/ContractFile.java
  src/main/java/be15fintomatokatchupbe/contract/command/domain/repository/ContractRepository.java
  src/main/java/be15fintomatokatchupbe/contract/exception/ContractErrorCode.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
Labels: fix

#97 Feat: 캠페인 수익 요약 조회 구현
  src/main/java/be15fintomatokatchupbe/dashboard/query/controller/CampaignDashboardQueryController.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueDTO.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/dto/response/CampaignGetRevenueResponse.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/mapper/CampaignDashboardQueryMapper.java
  src/main/java/be15fintomatokatchupbe/dashboard/query/service/CampaignDashboardQueryService.java
  src/main/resources/mappers/dashboard/CampaignDashboardQueryMapper.xml
Labels: feat

#102 계약 수정 기능 개발
  src/main/java/be15fintomatokatchupbe/campaign/command/application/controller/CampaignCommandController.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/dto/request/UpdateContractRequest.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/ContractCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/service/QuotationCommandService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/application/support/CampaignHelperService.java
  src/main/java/be15fintomatokatchupbe/campaign/command/domain/aggregate/entity/Pipeline.java
  src/main/java/be15fintomatokatchupbe/file/repository/FileRepository.java
  src/main/java/be15fintomatokatchupbe/file/service/FileService.java
Labels: feat
